# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='User',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='Assignments',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='Courses',
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='users',
            field=models.ManyToManyField(to='users.UserProfile'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProfile'),
        ),
    ]
