# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 11:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190508_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 13, 32, 14, 793858)),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Course'),
        ),
    ]
