# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 11:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190508_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 13, 42, 21, 611283)),
        ),
    ]
