# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-08 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190508_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 8, 13, 45, 40, 171826)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
