# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-02 21:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190602_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 2, 23, 22, 18, 161912)),
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set([('assignment', 'user')]),
        ),
    ]
