# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-02 23:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190602_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 1, 20, 49, 744498)),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(null=True, upload_to=users.models.get_submission_path),
        ),
    ]
