# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-03 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20190603_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 3, 3, 30, 25, 671152)),
        ),
    ]
